### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Rakleed** [ActivityWatch/aw-android#17] opened 2019-04-13 21:10 UTC
Please make a dark theme of the application.

**Comment by ErikBjare** [comment] 2019-04-14 08:51
Essentially a duplicate of https://github.com/ActivityWatch/activitywatch/issues/253.

Discussion moved to [the forum](https://forum.activitywatch.net/t/dark-theme-for-web-ui-and-android-app/274). Vote on the feature there so we can know how much interest there is!

**Closed by ErikBjare** 2019-04-14 08:51 UTC

**Comment by Rakleed** [comment] 2019-04-14 18:28
@ErikBjare Why don't you use reactions to messages on GitHub to evaluate the importance of a feature request? Just when each service creates its own forum for discussing proposals with necessary registration, it becomes inconvenient. And just need to have a GitHub account.

**Comment by ErikBjare** [comment] 2019-04-14 19:42
We've considered that before, but have decided otherwise because:

 - There's no well defined meaning to reactions. 
 - There's no way to easily show users a list of which features have been requested before (and which are the most requested ones) in a way that doesn't have terrible UX. 
 - We don't want to mix real issues with feature requests (as that leads to many indefinitely open issues that may or may not ever get dealt with). 
 - We want to cultivate a community, and a forum enables us to do that in a way that GitHub issues don't.

I could go on, but I think that is reasons enough. You can log onto the forum with your GitHub account, I don't see the inconvenience.

Hope the answer clears up our thinking for you :slight_smile:
