### ISSUE TITLE
Error while building the make file in aw-android

### ISSUE THREAD

**Issue by venkatasai2714** [ActivityWatch/aw-android#96] opened 2023-08-17 14:04 UTC
![Screenshot 2023-08-17 193209](https://github.com/ActivityWatch/aw-android/assets/82219320/3ee2d51d-f4ef-4372-9358-51d0f014b62b)

Getting error while running `make build`

**Comment by ErikBjare** [comment] 2023-08-30 12:58
Duplicate of #94

**Closed** 2023-08-30 12:58 UTC
Labels: duplicate
